name: Deploy

concurrency: deploy

on:
#  push:
#    branches:
#      - develop
  workflow_dispatch:

env:
  PROJECT_NAME: template-app

jobs:
  server:
    name: Build server
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: war
          build-root-directory: ./server
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Get Artifact name
        run: echo "ARTIFACT=$(find ./build/libs -name '*.war' | xargs basename)" >> $GITHUB_ENV
      - name: Upload to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: ./server/build/libs/${{ env.ARTIFACT }}
          target: ~/packages/${{ env.PROJECT_NAME }}/${{ github.ref_name }}/server
          strip_components: 1
      - name: Install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            find /opt/tomcat/webapps -name '${{ env.PROJECT_NAME }}*' | xargs rm -rf
            cp ~/packages/${{ env.PROJECT_NAME }}/${{ github.ref_name }}/server/${{ env.ARTIFACT }} /opt/tomcat/webapps
