name: Deploy

concurrency: deploy

on:
#  push:
#    branches:
#      - develop
  workflow_dispatch:

jobs:
  server:
    name: Build server
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build
        id: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: war
          build-root-directory: ./server
        env:
          BUILD_NUMBER: ${{ github.run_number }}
#      - name: Upload to VPS
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.KEY }}
#          source: ./server/build/libs/*.war
#          target: ~/packages/template-app/${{ github.ref_name }}/server
#          strip_components: 1
      - name: Install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "${{ steps.build.outputs }}"
#            systemctl stop tomcat
#            rm -rf /opt/tomcat/webapps/template-app
#            find /opt/tomcat/webapps "template-app*" | rm
#            cp ~/packages/template-app/${{ github.ref_name }}/server/
#            systemctl start tomcat

