name: Deploy

concurrency: deploy

on:
#  push:
#    branches:
#      - develop
  workflow_dispatch:

jobs:
  server:
    name: Build server
    runs-on: ubuntu-latest
    environment: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: ./gradlew war
        working-directory: ./server
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          source: "./server/build/libs/template-app-${{ github.run_number }}.war"
          target: "~/packages/template-app/${{ github.ref }}/server"
