name: Deploy

concurrency: deploy

on:
#  push:
#    branches:
#      - develop
  workflow_dispatch:

jobs:
  server:
    name: Build server
    runs-on: ubuntu-latest
    environment: ${{ github.ref }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Add permission for gradlew
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew war
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Upload to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          source: ./server/build/libs/template-app-${{ github.run_number }}.war
          target: ~/packages/template-app/${{ github.ref }}/server
