name: prod
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:

  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    defaults:
      run:
    steps:


  deploy-server:
    name: Deploy server
    runs-on: ubuntu-latest
    needs: build-server

  build-web:
    name: Build Web
    runs-on: ubuntu-latest

  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    needs: build-web
